//! tablepro captures (29): connections + workbench (drawer-mode 80x24)
//!
//! Ported verbatim from the retired tools/tuisnap_baseline.sh (capture
//! names, argv, needles, sends, CAP_TIMEOUTs). Do not hand-tune: drift
//! against the approved frames means the port or the app changed.

use crate::support::{Case, Color, TABLEPRO};

crate::baseline_case!(tablepro_connections_default_80x24_truecolor => Case::new("tablepro_connections_default_80x24_truecolor", TABLEPRO, &[], 80, 24, Color::Truecolor, "Production"));
crate::baseline_case!(tablepro_connections_default_120x40_truecolor => Case::new("tablepro_connections_default_120x40_truecolor", TABLEPRO, &[], 120, 40, Color::Truecolor, "Production"));
crate::baseline_case!(tablepro_connections_default_120x40_none => Case::new("tablepro_connections_default_120x40_none", TABLEPRO, &[], 120, 40, Color::None, "Production"));
crate::baseline_case!(tablepro_workbench_default_80x24_truecolor => Case::new("tablepro_workbench_default_80x24_truecolor", TABLEPRO, &["--connect", "Production"], 80, 24, Color::Truecolor, "Query 1"));
crate::baseline_case!(tablepro_workbench_default_120x40_truecolor => Case::new("tablepro_workbench_default_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1"));
crate::baseline_case!(tablepro_workbench_default_120x40_256 => Case::new("tablepro_workbench_default_120x40_256", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Ansi256, "Query 1"));
crate::baseline_case!(tablepro_workbench_default_120x40_16 => Case::new("tablepro_workbench_default_120x40_16", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Ansi16, "Query 1"));
crate::baseline_case!(tablepro_workbench_default_120x40_none => Case::new("tablepro_workbench_default_120x40_none", TABLEPRO, &["--connect", "Production"], 120, 40, Color::None, "Query 1"));
crate::baseline_case!(tablepro_workbench_default_120x40_nocolor => Case::new("tablepro_workbench_default_120x40_nocolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::NoColorEnv, "Query 1"));
crate::baseline_case!(tablepro_form_new_120x40_truecolor => Case::new("tablepro_form_new_120x40_truecolor", TABLEPRO, &[], 120, 40, Color::Truecolor, "Production").sends(&["ctrl-n"]));
crate::baseline_case!(tablepro_form_new_filled_120x40_truecolor => Case::new("tablepro_form_new-filled_120x40_truecolor", TABLEPRO, &[], 120, 40, Color::Truecolor, "Production").sends(&["ctrl-n", "type:Staging replica"]));
crate::baseline_case!(tablepro_table_data_120x40_truecolor => Case::new("tablepro_table_data_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders"]));
crate::baseline_case!(tablepro_table_structure_120x40_truecolor => Case::new("tablepro_table_structure_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders", "ctrl-d", "wait:Columns"]));
crate::baseline_case!(tablepro_table_sorted_120x40_truecolor => Case::new("tablepro_table_sorted_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders", "right", "right", "right", "right", "right", "right", "right", "right", "right", "right", "right", "right", "s", "wait:sort created_at ▴"]));
crate::baseline_case!(tablepro_table_filtered_120x40_truecolor => Case::new("tablepro_table_filtered_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders", "home", "right", "right", "right", "right", "f", "backtab", "backtab", "enter", "ctrl-l", "type:pending", "enter", "wait:filtered (1)"]));
crate::baseline_case!(tablepro_cell_editing_120x40_truecolor => Case::new("tablepro_cell_editing_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders", "home", "right", "right", "right", "right", "enter"]));
crate::baseline_case!(tablepro_row_duplicated_120x40_truecolor => Case::new("tablepro_row_duplicated_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["down", "down", "down", "down", "down", "enter", "wait:public › orders", "alt-d"]));
crate::baseline_case!(tablepro_query_completion_120x40_truecolor => Case::new("tablepro_query_completion_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:SELECT * FROM ord", "wait:order_items"]));
crate::baseline_case!(tablepro_query_results_120x40_truecolor => Case::new("tablepro_query_results_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:SELECT * FROM ord", "enter", "type: WHERE st", "tab", "type: = 'pending' ORDER BY created_at DESC LIMIT 25", "escape", "ctrl-r", "wait:25 rows"]));
crate::baseline_case!(tablepro_query_error_120x40_truecolor => Case::new("tablepro_query_error_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:SELECT * FROM missing_table", "escape", "ctrl-r", "sleep:800"]));
crate::baseline_case!(tablepro_query_explain_120x40_truecolor => Case::new("tablepro_query_explain_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:SELECT * FROM orders", "escape", "ctrl-x", "sleep:500"]));
crate::baseline_case!(tablepro_ack_gate_120x40_truecolor => Case::new("tablepro_ack_gate_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:UPDATE orders SET status = 'paid' WHERE id = 'x'", "escape", "ctrl-r", "wait:Type orders to confirm"]));
crate::baseline_case!(tablepro_ack_armed_120x40_truecolor => Case::new("tablepro_ack_armed_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:UPDATE orders SET status = 'paid' WHERE id = 'x'", "escape", "ctrl-r", "wait:Type orders to confirm", "enter", "type:orders", "enter", "right", "wait:Execute"]));
crate::baseline_case!(tablepro_ack_executed_120x40_truecolor => Case::new("tablepro_ack_executed_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["tab", "i", "type:UPDATE orders SET status = 'paid' WHERE id = 'x'", "escape", "ctrl-r", "wait:Type orders to confirm", "enter", "type:orders", "enter", "right", "enter", "wait:rows affected"]));
crate::baseline_case!(tablepro_history_tab_120x40_truecolor => Case::new("tablepro_history_tab_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["ctrl-y", "wait:History"]));
crate::baseline_case!(tablepro_picker_open_120x40_truecolor => Case::new("tablepro_picker_open_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["ctrl-o", "wait:Open Quickly"]));
crate::baseline_case!(tablepro_tablist_open_120x40_truecolor => Case::new("tablepro_tablist_open_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["ctrl-g"]));
crate::baseline_case!(tablepro_safemode_picker_120x40_truecolor => Case::new("tablepro_safemode_picker_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["ctrl-l", "wait:Safe Mode"]));
crate::baseline_case!(tablepro_help_overlay_120x40_truecolor => Case::new("tablepro_help_overlay_120x40_truecolor", TABLEPRO, &["--connect", "Production"], 120, 40, Color::Truecolor, "Query 1").sends(&["?", "wait:Keyboard"]));
