[package]
name = "holla"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "holla_app"
path = "src/lib.rs"

[[bin]]
name = "holla"
path = "src/main.rs"

[[test]]
name = "perf"
path = "tests/perf.rs"

[lints]
workspace = true

[dependencies]
junie-tui = { workspace = true, features = ["crossterm"] }

[dev-dependencies]
junie-tui-testing.workspace = true
