#!/usr/bin/env bash
# Headless capture harness.
#
#   tools/capture.sh start <cols> <rows> -- <binary> [arg ...]
#   tools/capture.sh keys <keys...>
#   tools/capture.sh mouse <x> <y> [move|click|wheelup|wheeldown]
#   tools/capture.sh shot <name>
#   tools/capture.sh resize <cols> <rows>
#   tools/capture.sh stop
#
# BIN is required and must equal the first argv element after `--`. Arguments
# are passed as an argv array to tmux and capture_exec.sh; they never become
# shell source. CAPTURE_RUN_ID is generated by start when omitted and is
# required for every operation that refers to an existing run.
set -euo pipefail
umask 077

cd "$(dirname "${BASH_SOURCE[0]}")/.."
ROOT_DIR=$(pwd -P)
PROVENANCE_TOOL=$ROOT_DIR/tools/capture_provenance.py
RUNNER=$ROOT_DIR/tools/capture_exec.sh

: "${BIN:?BIN must be set to the owning application binary}"
COLOR=${COLOR:-truecolor}
CAPTURE_DIR=${CAPTURE_DIR:-shots}
CAPTURE_MANIFEST=${CAPTURE_MANIFEST:-$CAPTURE_DIR/capture-provenance.json}
CAPTURE_STATE_DIR=${CAPTURE_STATE_DIR:-$CAPTURE_DIR/.capture-state}
PYTHON_BIN=${PY:-python3}
STATE_PYTHON=/usr/bin/python3
if [[ ! -x "$STATE_PYTHON" ]]; then
  echo "capture failed: trusted metadata Python is unavailable: $STATE_PYTHON" >&2
  exit 1
fi
cmd=${1:-}
shift || true

# A failed start must not leave a live tmux session or a half-owned run
# directory behind.  The session id is recorded as soon as tmux creates the
# session, so cleanup never kills a same-named session that replaced ours.
START_SESSION_ID=

cleanup_failed_start() {
  local status=$1 current path cleanup_failed=0
  trap - EXIT

  if (( status != 0 )); then
    if [[ -n "$START_SESSION_ID" ]] && session_exists; then
      current=$(session_id || true)
      if [[ "$current" == "$START_SESSION_ID" ]]; then
        if ! tmux kill-session -t "$SESSION_NAME" 2>/dev/null; then
          cleanup_failed=1
          echo "capture cleanup failed: cannot kill owned tmux session $SESSION_NAME" >&2
        fi
      elif [[ -z "$current" ]]; then
        cleanup_failed=1
        echo "capture cleanup failed: cannot verify tmux session ownership for $SESSION_NAME" >&2
      fi
    fi

    # Keep state when cleanup itself fails.  The caller can then report or
    # retry an explicit stop; deleting unverifiable state would hide a leak.
    if (( cleanup_failed == 0 )); then
      for path in \
        "$RUN_METADATA_FILE" \
        "$RUN_SESSION_ID_FILE" \
        "$RUN_EXIT_FILE" \
        "$RUN_BIN_FILE" \
        "$RUN_EXECUTABLE_FILE" \
        "$RUN_CAPTURE_DIR_FILE" \
        "$RUN_MANIFEST_FILE" \
        "$RUN_STDERR_FILE" \
        "$RUN_COLOR_FILE" \
        "$STDERR_FILE"; do
        if [[ -L "$path" ]]; then
          cleanup_failed=1
          echo "capture cleanup failed: refusing symlink state $path" >&2
        elif [[ -e "$path" ]] && ! rm -f "$path"; then
          cleanup_failed=1
          echo "capture cleanup failed: cannot remove $path" >&2
        fi
      done
      for path in "$RUN_DIR"/*.tmp.* "$RUN_DIR"/.*.tmp; do
        if [[ -L "$path" ]]; then
          cleanup_failed=1
          echo "capture cleanup failed: refusing symlink temporary $path" >&2
        elif [[ -e "$path" ]] && ! rm -f "$path"; then
          cleanup_failed=1
          echo "capture cleanup failed: cannot remove $path" >&2
        fi
      done
      if (( cleanup_failed == 0 )) && ! rmdir "$RUN_DIR" 2>/dev/null; then
        cleanup_failed=1
        echo "capture cleanup failed: cannot remove run state $RUN_DIR" >&2
      fi
    fi
    if (( cleanup_failed != 0 )); then
      echo "capture cleanup incomplete; run state retained: $RUN_DIR" >&2
    fi
  fi
  exit "$status"
}

absolute_path() {
  case "$1" in
    /*) printf '%s\n' "$1" ;;
    *) printf '%s/%s\n' "$ROOT_DIR" "$1" ;;
  esac
}

reject_newline() {
  local label=$1 value=$2
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
    echo "capture failed: $label may not contain a newline" >&2
    return 1
  fi
}

validate_run_id() {
  if [[ ! "$1" =~ ^[A-Za-z0-9_-]{1,64}$ ]]; then
    echo "capture failed: unsafe CAPTURE_RUN_ID: $1" >&2
    return 1
  fi
}

validate_dimensions() {
  local cols=$1 rows=$2
  if [[ ! "$cols" =~ ^[0-9]+$ || ! "$rows" =~ ^[0-9]+$ ]] || (( cols < 1 || rows < 1 )); then
    echo "capture failed: dimensions must be positive integers (got ${cols}x${rows})" >&2
    return 1
  fi
}

ensure_directory() {
  local path=$1 label=$2
  if [[ -L "$path" ]]; then
    echo "capture failed: $label is a symlink: $path" >&2
    return 1
  fi
  if [[ -e "$path" && ! -d "$path" ]]; then
    echo "capture failed: $label is not a directory: $path" >&2
    return 1
  fi
  mkdir -p "$path"
  if [[ -L "$path" || ! -d "$path" ]]; then
    echo "capture failed: $label is not a safe directory: $path" >&2
    return 1
  fi
}

ensure_state_target() {
  local path=$1 label=$2
  if [[ -L "$path" ]]; then
    echo "capture failed: $label is a symlink: $path" >&2
    return 1
  fi
  if [[ -e "$path" && ! -f "$path" ]]; then
    echo "capture failed: $label is not a regular file: $path" >&2
    return 1
  fi
}

write_state() {
  local path=$1 value=$2 temporary
  ensure_state_target "$path" "capture state"
  temporary=$(mktemp "${path}.tmp.XXXXXX")
  chmod 600 "$temporary"
  printf '%s\n' "$value" > "$temporary"
  mv -f "$temporary" "$path"
}

state_value() {
  local path=$1 fallback=$2
  if ! "$STATE_PYTHON" "$PROVENANCE_TOOL" read-state --path "$path" 2>/dev/null; then
    printf '%s\n' "$fallback"
  fi
}

required_state() {
  local path=$1 label=$2 value
  if ! value=$("$STATE_PYTHON" "$PROVENANCE_TOOL" read-state --path "$path"); then
    echo "capture failed: $label is missing or unsafe: $path" >&2
    return 1
  fi
  if [[ -z "$value" ]]; then
    echo "capture failed: $label is empty: $path" >&2
    return 1
  fi
  printf '%s\n' "$value"
}

validate_capture_name() {
  local name=$1
  if [[ ! "$name" =~ ^[A-Za-z0-9][A-Za-z0-9_-]*$ ]]; then
    echo "capture failed: unsafe capture name: $name" >&2
    return 1
  fi
}

validate_binary() {
  if [[ "$BIN" == *$'\n'* || "$BIN" == *$'\r'* || ! -f "$BIN" || ! -x "$BIN" ]]; then
    echo "capture failed: BIN is not an executable regular file: $BIN" >&2
    return 1
  fi
}

new_run_id() {
  printf '%s-%s-%s-%s\n' \
    "$(date -u +%Y%m%dT%H%M%SZ)" "$$" "${BASHPID:-$$}" "$RANDOM"
}

session_id() {
  tmux display-message -p -t "$SESSION_NAME" '#{session_id}' 2>/dev/null
}

session_exists() {
  tmux has-session -t "$SESSION_NAME" 2>/dev/null
}

require_owned_session() {
  local actual expected
  if ! session_exists; then
    echo "capture failed: owned tmux session '$SESSION_NAME' is not running" >&2
    return 1
  fi
  expected=$(required_state "$RUN_SESSION_ID_FILE" "session id")
  if ! actual=$(session_id) || [[ -z "$actual" || "$actual" != "$expected" ]]; then
    echo "capture failed: tmux session '$SESSION_NAME' is stale or not owned by run $CAPTURE_RUN_ID" >&2
    return 1
  fi
}

configure_session() {
  tmux set-option -t "$SESSION_NAME" status off 2>/dev/null || return 1
  tmux set-option -s escape-time 0 2>/dev/null || return 1
  tmux set-option -g default-terminal "tmux-256color" 2>/dev/null || return 1
  tmux set-option -ga terminal-overrides ",*:Tc" 2>/dev/null || return 1
}

read_exit_status() {
  if [[ -s "$RUN_EXIT_FILE" && ! -L "$RUN_EXIT_FILE" ]]; then
    state_value "$RUN_EXIT_FILE" unknown
  elif session_exists && require_owned_session >/dev/null 2>&1; then
    printf '%s\n' running
  else
    printf '%s\n' unknown
  fi
}

capture_theme() {
  if [[ -n "${THEME:-}" ]]; then
    printf '%s\n' "$THEME"
    return
  fi
  local index argument
  for ((index = 0; index < ${#APP_ARGV[@]}; index += 1)); do
    argument=${APP_ARGV[index]}
    case "$argument" in
      --theme=*) printf '%s\n' "${argument#--theme=}"; return ;;
      --theme)
        if (( index + 1 < ${#APP_ARGV[@]} )); then
          printf '%s\n' "${APP_ARGV[index + 1]}"
          return
        fi
        ;;
    esac
  done
  printf '%s\n' junie
}

tool_version() {
  local tool=$1 version_flag=${2:---version}
  "$tool" "$version_flag" 2>&1 | sed -n '1p'
}

snapshot_value() {
  local name=$1
  # `${!name+x}` is supported by macOS Bash 3.2; `[[ -v ]]` is Bash 4+.
  if [[ -n "${!name+x}" ]]; then
    printf '%s=%s\n' "$name" "${!name}"
  else
    printf '%s=<unset>\n' "$name"
  fi
}

finalize_provenance() {
  local exit_status=$1
  "$STATE_PYTHON" "$PROVENANCE_TOOL" finalize \
    --metadata "$RUN_METADATA_FILE" \
    --manifest "$CAPTURE_MANIFEST_PATH" \
    --run-id "$CAPTURE_RUN_ID" \
    --exit-status "$exit_status" \
    --stderr "$STDERR_FILE"
}

record_provenance() {
  local name=$1 columns=$2 rows=$3 status=$4 exit_status=$5
  local ansi_path=$6 cursor_path=$7 text_path=$8 html_path=$9 png_path=${10}
  "$STATE_PYTHON" "$PROVENANCE_TOOL" record \
    --metadata "$RUN_METADATA_FILE" \
    --manifest "$CAPTURE_MANIFEST_PATH" \
    --run-id "$CAPTURE_RUN_ID" \
    --name "$name" \
    --columns "$columns" \
    --rows "$rows" \
    --status "$status" \
    --exit-status "$exit_status" \
    --stderr "$STDERR_FILE" \
    --artifact "ansi=$ansi_path" \
    --artifact "cursor=$cursor_path" \
    --artifact "txt=$text_path" \
    --artifact "html=$html_path" \
    --artifact "png=$png_path"
}

remove_generation_dir() {
  local directory=$1 artifact path
  if [[ -L "$directory" || ! -d "$directory" ]]; then
    echo "capture failed: generation is not a real directory: $directory" >&2
    return 1
  fi
  for artifact in ansi cursor txt html png; do
    path=$directory/$artifact
    if [[ -L "$path" ]]; then
      echo "capture failed: refusing symlink generation artifact: $path" >&2
      return 1
    fi
    if [[ -e "$path" && ! -f "$path" ]]; then
      echo "capture failed: generation artifact is not a regular file: $path" >&2
      return 1
    fi
    if [[ -e "$path" ]] && ! rm -f "$path"; then
      echo "capture failed: cannot remove generation artifact: $path" >&2
      return 1
    fi
  done
  if ! rmdir "$directory"; then
    echo "capture failed: generation directory is not empty: $directory" >&2
    return 1
  fi
}

move_failed_generation_aside() {
  local source=$1 destination=$2
  if [[ -L "$source" || ! -d "$source" ]]; then
    echo "capture failed: cannot quarantine unsafe generation: $source" >&2
    return 1
  fi
  if [[ -e "$destination" || -L "$destination" ]]; then
    echo "capture failed: generation quarantine already exists: $destination" >&2
    return 1
  fi
  mv "$source" "$destination"
}

SHOT_LOCK_DIR=
SHOT_LOCK_GUARD=
SHOT_LOCK_OWNER=

release_shot_lock() {
  if [[ -z "$SHOT_LOCK_DIR" ]]; then
    return 0
  fi
  if ! "$STATE_PYTHON" "$PROVENANCE_TOOL" shot-lock release \
    --lock "$SHOT_LOCK_DIR" \
    --guard "$SHOT_LOCK_GUARD" \
    --owner "$SHOT_LOCK_OWNER"; then
    echo "capture cleanup failed: cannot release shot lock: $SHOT_LOCK_DIR" >&2
    return 1
  fi
  SHOT_LOCK_DIR=
  SHOT_LOCK_GUARD=
  SHOT_LOCK_OWNER=
}

cleanup_shot_lock_only() {
  local status=$?
  trap - EXIT
  if ! release_shot_lock && (( status == 0 )); then
    status=1
  fi
  exit "$status"
}

acquire_shot_lock() {
  local name=$1
  SHOT_LOCK_DIR=$CAPTURE_DIR_PATH/.${name}.lock
  SHOT_LOCK_GUARD=$CAPTURE_DIR_PATH/.${name}.lock.guard
  SHOT_LOCK_OWNER="$$:$CAPTURE_RUN_ID"
  "$STATE_PYTHON" "$PROVENANCE_TOOL" shot-lock acquire \
    --lock "$SHOT_LOCK_DIR" \
    --guard "$SHOT_LOCK_GUARD" \
    --owner "$SHOT_LOCK_OWNER"
}

load_run_state() {
  validate_run_id "$CAPTURE_RUN_ID"
  STATE_ROOT_PATH=$(absolute_path "$CAPTURE_STATE_DIR")
  if [[ -L "$STATE_ROOT_PATH" || ! -d "$STATE_ROOT_PATH" ]]; then
    echo "capture failed: capture state directory is missing or unsafe: $STATE_ROOT_PATH" >&2
    return 1
  fi
  RUN_DIR=$STATE_ROOT_PATH/$CAPTURE_RUN_ID
  if [[ -L "$RUN_DIR" || ! -d "$RUN_DIR" ]]; then
    echo "capture failed: run state is missing or unsafe: $RUN_DIR" >&2
    return 1
  fi
  RUN_METADATA_FILE=$RUN_DIR/metadata.json
  RUN_SESSION_ID_FILE=$RUN_DIR/session.id
  RUN_EXIT_FILE=$RUN_DIR/exit.status
  RUN_BIN_FILE=$RUN_DIR/bin
  RUN_CAPTURE_DIR_FILE=$RUN_DIR/capture.dir
  RUN_MANIFEST_FILE=$RUN_DIR/manifest
  RUN_STDERR_FILE=$RUN_DIR/stderr
  RUN_COLOR_FILE=$RUN_DIR/color
  SESSION_NAME="junie_cap_${CAPTURE_RUN_ID}"

  local stored_bin stored_capture_dir stored_manifest stored_stderr
  stored_bin=$(required_state "$RUN_BIN_FILE" "binary state")
  if [[ "$BIN" != "$stored_bin" ]]; then
    echo "capture failed: BIN does not match the owning run" >&2
    return 1
  fi
  stored_capture_dir=$(required_state "$RUN_CAPTURE_DIR_FILE" "capture directory state")
  stored_manifest=$(required_state "$RUN_MANIFEST_FILE" "manifest state")
  stored_stderr=$(required_state "$RUN_STDERR_FILE" "stderr state")
  CAPTURE_DIR_PATH=$stored_capture_dir
  CAPTURE_MANIFEST_PATH=$stored_manifest
  STDERR_FILE=$stored_stderr
  if [[ ! -f "$RUN_METADATA_FILE" || -L "$RUN_METADATA_FILE" ]]; then
    echo "capture failed: run provenance state is missing or unsafe" >&2
    return 1
  fi
}

case "$cmd" in
  start)
    cols=${1:-120}
    rows=${2:-40}
    shift 2 || true
    validate_dimensions "$cols" "$rows"
    reject_newline "BIN" "$BIN"
    validate_binary
    legacy_args_variable=ARGS
    if [[ -n "${!legacy_args_variable-}" ]]; then
      echo "capture failed: ARGS is unsupported; pass exact argv after --" >&2
      exit 1
    fi
    if [[ "${1:-}" == "--" ]]; then
      shift
      APP_ARGV=("$@")
    else
      if (( $# != 0 )); then
        echo "capture failed: pass application arguments after --" >&2
        exit 1
      fi
      APP_ARGV=("$BIN")
    fi
    if (( ${#APP_ARGV[@]} == 0 )) || [[ "${APP_ARGV[0]}" != "$BIN" ]]; then
      echo "capture failed: argv must begin with BIN after --" >&2
      exit 1
    fi
    if [[ -n "${CAPTURE_RUN_ID:-}" ]]; then
      validate_run_id "$CAPTURE_RUN_ID"
    else
      CAPTURE_RUN_ID=$(new_run_id)
    fi
    validate_run_id "$CAPTURE_RUN_ID"
    SESSION_NAME="junie_cap_${CAPTURE_RUN_ID}"
    if session_exists; then
      echo "capture failed: capture session already exists: $SESSION_NAME" >&2
      exit 1
    fi
    STATE_ROOT_PATH=$(absolute_path "$CAPTURE_STATE_DIR")
    CAPTURE_DIR_PATH=$(absolute_path "$CAPTURE_DIR")
    CAPTURE_MANIFEST_PATH=$(absolute_path "$CAPTURE_MANIFEST")
    ensure_directory "$CAPTURE_DIR_PATH" "capture directory"
    ensure_directory "$(dirname "$CAPTURE_MANIFEST_PATH")" "manifest parent"
    ensure_directory "$STATE_ROOT_PATH" "capture state directory"
    RUN_DIR=$STATE_ROOT_PATH/$CAPTURE_RUN_ID
    if [[ -e "$RUN_DIR" || -L "$RUN_DIR" ]]; then
      echo "capture failed: run state already exists: $RUN_DIR" >&2
      exit 1
    fi
    mkdir -m 700 "$RUN_DIR"
    RUN_METADATA_FILE=$RUN_DIR/metadata.json
    RUN_SESSION_ID_FILE=$RUN_DIR/session.id
    RUN_EXIT_FILE=$RUN_DIR/exit.status
    RUN_BIN_FILE=$RUN_DIR/bin
    RUN_EXECUTABLE_FILE=$RUN_DIR/executable
    RUN_CAPTURE_DIR_FILE=$RUN_DIR/capture.dir
    RUN_MANIFEST_FILE=$RUN_DIR/manifest
    RUN_STDERR_FILE=$RUN_DIR/stderr
    RUN_COLOR_FILE=$RUN_DIR/color
    # Keep per-run stderr inside the ignored, mode-0700 state directory so
    # concurrent captures never share or leave a global stderr artifact.
    STDERR_FILE=$RUN_DIR/stderr.log
    trap 'cleanup_failed_start "$?"' EXIT
    theme=$(capture_theme)
    case "$COLOR" in
      truecolor)
        effective_no_color='<unset>'
        effective_term=xterm-256color
        effective_colorterm=truecolor
        ;;
      256)
        effective_no_color='<unset>'
        effective_term=xterm-256color
        effective_colorterm='<unset>'
        ;;
      16)
        effective_no_color='<unset>'
        effective_term=xterm
        effective_colorterm='<unset>'
        ;;
      mono)
        effective_no_color=1
        effective_term=xterm-256color
        effective_colorterm=truecolor
        ;;
      *)
        echo "unknown COLOR: $COLOR (truecolor|256|16|mono)" >&2
        exit 1
        ;;
    esac
    revision=$(git rev-parse --verify HEAD 2>/dev/null) || {
      echo "capture failed: cannot determine Git revision" >&2
      exit 1
    }
    if [[ ! "$revision" =~ ^[0-9a-fA-F]{40}$ ]]; then
      echo "capture failed: Git revision is not a full commit id: $revision" >&2
      exit 1
    fi
    dirty=false
    if [[ -n "$(git status --porcelain --untracked-files=all)" ]]; then
      dirty=true
    fi
    python_path=$(command -v "$PYTHON_BIN") || {
      echo "capture failed: PNG Python interpreter is not available: $PYTHON_BIN" >&2
      exit 1
    }
    tool_env=(
      --env "COLOR=$COLOR"
      --env "NO_COLOR=$effective_no_color"
      --env "TERM=$effective_term"
      --env "COLORTERM=$effective_colorterm"
      --env "LANG=$(snapshot_value LANG | sed 's/^LANG=//')"
      --env "LC_ALL=$(snapshot_value LC_ALL | sed 's/^LC_ALL=//')"
      --env "LC_CTYPE=$(snapshot_value LC_CTYPE | sed 's/^LC_CTYPE=//')"
      --env "LANGUAGE=$(snapshot_value LANGUAGE | sed 's/^LANGUAGE=//')"
      --env "TZ=$(snapshot_value TZ | sed 's/^TZ=//')"
      --env "PYTHONHASHSEED=$(snapshot_value PYTHONHASHSEED | sed 's/^PYTHONHASHSEED=//')"
      --env "SOURCE_DATE_EPOCH=$(snapshot_value SOURCE_DATE_EPOCH | sed 's/^SOURCE_DATE_EPOCH=//')"
      --env "PATH=$(snapshot_value PATH | sed 's/^PATH=//')"
      --env "HOME=$(snapshot_value HOME | sed 's/^HOME=//')"
      --env "USER=$(snapshot_value USER | sed 's/^USER=//')"
      --env "LOGNAME=$(snapshot_value LOGNAME | sed 's/^LOGNAME=//')"
      --env "SHELL=$(snapshot_value SHELL | sed 's/^SHELL=//')"
      --env "PWD=$(snapshot_value PWD | sed 's/^PWD=//')"
      --env "TMPDIR=$(snapshot_value TMPDIR | sed 's/^TMPDIR=//')"
    )
    tool_versions=(
      --tool "bash=$BASH_VERSION"
      --tool "tmux=$(tool_version tmux -V)"
      --tool "python3=$(tool_version "$STATE_PYTHON")"
      --tool "png-python=$(tool_version "$PYTHON_BIN")"
      --tool "git=$(tool_version git)"
    )
    tool_files=(
      --tool-file "capture.sh=$ROOT_DIR/tools/capture.sh"
      --tool-file "capture_exec.sh=$RUNNER"
      --tool-file "capture_provenance.py=$PROVENANCE_TOOL"
      --tool-file "ansi2html.py=$ROOT_DIR/tools/ansi2html.py"
      --tool-file "ansi2png.py=$ROOT_DIR/tools/ansi2png.py"
      --tool-file "png-python=$python_path"
    )
    write_state "$RUN_BIN_FILE" "$BIN"
    write_state "$RUN_CAPTURE_DIR_FILE" "$CAPTURE_DIR_PATH"
    write_state "$RUN_MANIFEST_FILE" "$CAPTURE_MANIFEST_PATH"
    write_state "$RUN_STDERR_FILE" "$STDERR_FILE"
    write_state "$RUN_COLOR_FILE" "$COLOR"
    "$STATE_PYTHON" "$PROVENANCE_TOOL" stage-binary \
      --source "$BIN" \
      --destination "$RUN_EXECUTABLE_FILE"
    "$STATE_PYTHON" "$PROVENANCE_TOOL" init \
      --metadata "$RUN_METADATA_FILE" \
      --run-id "$CAPTURE_RUN_ID" \
      --session "$SESSION_NAME" \
      --session-id pending \
      --binary "$RUN_EXECUTABLE_FILE" \
      --source-binary "$BIN" \
      --revision "$revision" \
      --dirty "$dirty" \
      --columns "$cols" \
      --rows "$rows" \
      --capture-dir "$CAPTURE_DIR_PATH" \
      --manifest "$CAPTURE_MANIFEST_PATH" \
      --stderr "$STDERR_FILE" \
      --theme "$theme" \
      --color "$COLOR" \
      "${tool_env[@]}" \
      "${tool_versions[@]}" \
      "${tool_files[@]}" \
      --argv "${APP_ARGV[@]}"
    if ! actual_session_id=$(tmux -f /dev/null new-session -d -P -F '#{session_id}' \
      -s "$SESSION_NAME" -c "$ROOT_DIR" -x "$cols" -y "$rows" \
      -e "CAPTURE_METADATA_FILE=$RUN_METADATA_FILE" \
      -e "CAPTURE_RUN_ID=$CAPTURE_RUN_ID" \
      -e "CAPTURE_STDERR_FILE=$STDERR_FILE" \
      -e "CAPTURE_EXIT_FILE=$RUN_EXIT_FILE" \
      -e "CAPTURE_COLOR_MODE=$COLOR" \
      /bin/bash tools/capture_exec.sh \
    ); then
      # A server can create a session before reporting a command error.  The
      # printed id is authoritative only when the named session still has it;
      # otherwise leave an unverified session untouched for safety.
      if [[ -n "$actual_session_id" ]] && session_exists; then
        current_session_id=$(session_id || true)
        if [[ "$current_session_id" == "$actual_session_id" ]]; then
          START_SESSION_ID=$actual_session_id
        fi
      fi
      echo "capture failed: tmux could not start the owning session" >&2
      exit 1
    fi
    if ! session_exists; then
      exit_status=$(read_exit_status)
      echo "capture failed: tmux session ended during setup (app exit status $exit_status); stderr: $STDERR_FILE" >&2
      exit 1
    fi
    if [[ -z "$actual_session_id" ]]; then
      echo "capture failed: tmux did not return a session id" >&2
      exit 1
    fi
    START_SESSION_ID=$actual_session_id
    write_state "$RUN_SESSION_ID_FILE" "$actual_session_id"
    "$STATE_PYTHON" "$PROVENANCE_TOOL" set-session \
      --metadata "$RUN_METADATA_FILE" \
      --run-id "$CAPTURE_RUN_ID" \
      --session-id "$actual_session_id"
    if ! configure_session; then
      exit_status=$(read_exit_status)
      echo "capture failed: tmux session ended during setup (app exit status $exit_status); stderr: $STDERR_FILE" >&2
      exit 1
    fi
    sleep 0.6
    if [[ -s "$RUN_EXIT_FILE" ]]; then
      exit_status=$(read_exit_status)
      echo "capture failed: $BIN exited before capture (status $exit_status); stderr: $STDERR_FILE" >&2
      exit 1
    fi
    if ! require_owned_session; then
      echo "capture failed: owned tmux session ended before capture; stderr: $STDERR_FILE" >&2
      exit 1
    fi
    trap - EXIT
    echo "$CAPTURE_RUN_ID"
    ;;
  keys)
    load_run_state
    require_owned_session
    for key in "$@"; do
      tmux send-keys -t "$SESSION_NAME" "$key"
      sleep 0.08
    done
    sleep 0.15
    ;;
  mouse)
    load_run_state
    require_owned_session
    x=${1:-}; y=${2:-}; kind=${3:-move}
    if [[ ! "$x" =~ ^[0-9]+$ || ! "$y" =~ ^[0-9]+$ ]]; then
      echo "capture failed: mouse coordinates must be positive integers" >&2
      exit 1
    fi
    case "$kind" in
      move)      sequence=$(printf '\e[<35;%d;%dM' "$x" "$y") ;;
      click)     sequence=$(printf '\e[<0;%d;%dM\e[<0;%d;%dm' "$x" "$y" "$x" "$y") ;;
      rclick)    sequence=$(printf '\e[<2;%d;%dM\e[<2;%d;%dm' "$x" "$y" "$x" "$y") ;;
      down)      sequence=$(printf '\e[<0;%d;%dM' "$x" "$y") ;;
      up)        sequence=$(printf '\e[<0;%d;%dm' "$x" "$y") ;;
      drag)      sequence=$(printf '\e[<32;%d;%dM' "$x" "$y") ;;
      wheelup)   sequence=$(printf '\e[<64;%d;%dM' "$x" "$y") ;;
      wheeldown) sequence=$(printf '\e[<65;%d;%dM' "$x" "$y") ;;
      *) echo "capture failed: unknown mouse action: $kind" >&2; exit 1 ;;
    esac
    tmux send-keys -t "$SESSION_NAME" -l "$sequence"
    sleep 0.15
    ;;
  shot)
    name=${1:-shot}
    validate_capture_name "$name"
    load_run_state
    require_owned_session
    ensure_directory "$CAPTURE_DIR_PATH" "capture directory"
    acquire_shot_lock "$name"
    trap cleanup_shot_lock_only EXIT
    cols=$(tmux display -p -t "$SESSION_NAME" '#{pane_width}')
    rows=$(tmux display -p -t "$SESSION_NAME" '#{pane_height}')
    validate_dimensions "$cols" "$rows"
    final_dir=$CAPTURE_DIR_PATH/$name
    if [[ -L "$final_dir" || ( -e "$final_dir" && ! -d "$final_dir" ) ]]; then
      echo "capture failed: final generation is not a safe directory: $final_dir" >&2
      exit 1
    fi
    ansi_path=$final_dir/ansi
    cursor_path=$final_dir/cursor
    text_path=$final_dir/txt
    html_path=$final_dir/html
    png_path=$final_dir/png
    stage_dir=
    backup_dir=$CAPTURE_DIR_PATH/.${name}.previous.$CAPTURE_RUN_ID
    failed_dir=$CAPTURE_DIR_PATH/.${name}.failed.$CAPTURE_RUN_ID
    if [[ -e "$backup_dir" || -L "$backup_dir" || -e "$failed_dir" || -L "$failed_dir" ]]; then
      echo "capture failed: stale transactional capture state exists for $name" >&2
      exit 1
    fi
    if ! stage_dir=$(mktemp -d "$CAPTURE_DIR_PATH/.${name}.staging.XXXXXX"); then
      echo "capture failed: cannot create staging generation for $name" >&2
      exit 1
    fi
    if [[ -L "$stage_dir" || ! -d "$stage_dir" ]]; then
      echo "capture failed: staging generation is not a safe directory: $stage_dir" >&2
      exit 1
    fi
    stage_ansi=$stage_dir/ansi
    stage_cursor=$stage_dir/cursor
    stage_text=$stage_dir/txt
    stage_html=$stage_dir/html
    stage_png=$stage_dir/png
    temporary_artifacts=()
    staged_artifacts=("$stage_ansi" "$stage_cursor" "$stage_text" "$stage_html" "$stage_png")
    cleanup_temporary_artifacts() {
      local status=$? temporary artifact
      trap - EXIT
      if (( ${#temporary_artifacts[@]} > 0 )); then
        for temporary in "${temporary_artifacts[@]}"; do
          if [[ -L "$temporary" ]]; then
            echo "capture cleanup failed: refusing symlink temporary $temporary" >&2
          elif [[ -e "$temporary" ]]; then
            rm -f "$temporary" || true
          fi
        done
      fi
      if (( ${#staged_artifacts[@]} > 0 )); then
        for artifact in "${staged_artifacts[@]}"; do
          if [[ -L "$artifact" ]]; then
            echo "capture cleanup failed: refusing symlink staged artifact $artifact" >&2
          elif [[ -e "$artifact" ]]; then
            rm -f "$artifact" || true
          fi
        done
      fi
      if [[ -n "$stage_dir" && -d "$stage_dir" && ! -L "$stage_dir" ]]; then
        rmdir "$stage_dir" 2>/dev/null || true
      fi
      release_shot_lock || true
      exit "$status"
    }
    trap cleanup_temporary_artifacts EXIT
    ansi_tmp=$(mktemp "$stage_dir/.ansi.XXXXXX")
    cursor_tmp=$(mktemp "$stage_dir/.cursor.XXXXXX")
    text_tmp=$(mktemp "$stage_dir/.txt.XXXXXX")
    html_tmp=$(mktemp "$stage_dir/.html.XXXXXX")
    png_tmp=$(mktemp "$stage_dir/.png.XXXXXX")
    temporary_artifacts=("$ansi_tmp" "$cursor_tmp" "$text_tmp" "$html_tmp" "$png_tmp")
    tmux capture-pane -t "$SESSION_NAME" -e -p -N > "$ansi_tmp"
    tmux display -p -t "$SESSION_NAME" '#{cursor_x} #{cursor_y} #{cursor_flag}' > "$cursor_tmp"
    tmux capture-pane -t "$SESSION_NAME" -p > "$text_tmp"
    mv -f "$ansi_tmp" "$stage_ansi"
    mv -f "$cursor_tmp" "$stage_cursor"
    mv -f "$text_tmp" "$stage_text"
    conversion_failed=0
    if ! "$STATE_PYTHON" "$ROOT_DIR/tools/ansi2html.py" "$stage_ansi" "$html_tmp" "$cols" "$rows"; then
      echo "capture failed: ansi2html could not convert $stage_ansi" >&2
      conversion_failed=1
    else
      mv -f "$html_tmp" "$stage_html"
    fi
    if ! "$PYTHON_BIN" "$ROOT_DIR/tools/ansi2png.py" "$stage_ansi" "$png_tmp" "$cols" "$rows" "$stage_cursor"; then
      echo "capture failed: ansi2png could not convert $stage_ansi" >&2
      conversion_failed=1
    else
      mv -f "$png_tmp" "$stage_png"
    fi

    exit_status=$(read_exit_status)
    app_failed=0
    if [[ "$exit_status" =~ ^-?[0-9]+$ ]] && (( exit_status != 0 )); then
      echo "capture failed: $BIN exited with status $exit_status; stderr: $STDERR_FILE" >&2
      app_failed=1
    fi
    if [[ -s "$STDERR_FILE" ]]; then
      echo "capture warning: application stderr is non-empty; inspect $STDERR_FILE" >&2
    fi

    artifact_failed=0
    for artifact in "${staged_artifacts[@]}"; do
      if [[ ! -s "$artifact" || -L "$artifact" || ! -f "$artifact" ]]; then
        echo "capture failed: artifact is missing, empty, or unsafe: $artifact" >&2
        artifact_failed=1
      fi
    done

    capture_status=ok
    if (( conversion_failed != 0 || app_failed != 0 || artifact_failed != 0 )); then
      capture_status=failed
    fi
    if [[ "$capture_status" == failed ]]; then
      # Failed conversions never replace an older complete generation.  The
      # failure record points at the published paths, not ephemeral staging.
      if ! record_provenance "$name" "$cols" "$rows" "$capture_status" "$exit_status" \
        "$ansi_path" "$cursor_path" "$text_path" "$html_path" "$png_path"; then
        echo "capture failed: cannot record failed capture provenance" >&2
      fi
      exit 1
    fi

    backup_moved=0
    if [[ -d "$final_dir" ]]; then
      if ! mv "$final_dir" "$backup_dir"; then
        echo "capture failed: cannot stage previous generation for $name" >&2
        exit 1
      fi
      backup_moved=1
    fi
    if ! mv "$stage_dir" "$final_dir"; then
      if (( backup_moved != 0 )); then
        mv "$backup_dir" "$final_dir" || true
        backup_moved=0
      fi
      echo "capture failed: cannot publish complete generation for $name" >&2
      exit 1
    fi
    stage_dir=
    staged_artifacts=()

    rollback_publication() {
      local rollback_failed=0
      if [[ -d "$final_dir" && ! -L "$final_dir" ]]; then
        if ! move_failed_generation_aside "$final_dir" "$failed_dir"; then
          rollback_failed=1
        fi
      fi
      if (( backup_moved != 0 )); then
        if ! mv "$backup_dir" "$final_dir"; then
          rollback_failed=1
        else
          backup_moved=0
        fi
      fi
      if [[ -d "$failed_dir" && ! -L "$failed_dir" ]]; then
        remove_generation_dir "$failed_dir" || rollback_failed=1
      fi
      return "$rollback_failed"
    }
    if ! record_provenance "$name" "$cols" "$rows" "$capture_status" "$exit_status" \
      "$ansi_path" "$cursor_path" "$text_path" "$html_path" "$png_path"; then
      if ! rollback_publication; then
        echo "capture failed: provenance failed and previous generation rollback failed" >&2
      fi
      exit 1
    fi
    if (( backup_moved != 0 )); then
      if ! remove_generation_dir "$backup_dir"; then
        echo "capture warning: previous generation retained at $backup_dir" >&2
      else
        backup_moved=0
      fi
    fi
    echo "$html_path ($cols x $rows; run=$CAPTURE_RUN_ID; color=$(state_value "$RUN_COLOR_FILE" "$COLOR"); provenance=$CAPTURE_MANIFEST_PATH)"
    ;;
  resize)
    load_run_state
    require_owned_session
    validate_dimensions "${1:-}" "${2:-}"
    tmux resize-window -t "$SESSION_NAME" -x "$1" -y "$2"
    sleep 0.3
    ;;
  stop)
    load_run_state
    final_exit_status=$(read_exit_status)
    if session_exists; then
      require_owned_session
      if [[ "$final_exit_status" == running || "$final_exit_status" == unknown ]]; then
        final_exit_status=terminated_by_capture_stop
      fi
      tmux kill-session -t "$SESSION_NAME"
    elif [[ "$final_exit_status" == unknown ]]; then
      echo "capture failed: run has no live owned session or recorded exit status" >&2
      exit 1
    fi
    finalize_provenance "$final_exit_status"
    ;;
  *)
    echo "unknown: $cmd" >&2
    exit 1
    ;;
esac
